server/config/routes.rb
Rails.application.routes.draw do
  resources :promociones
  resources :categorias
  resources :changos do
    member do
      get 'qr'
      get 'insertar_tag/:rfid', action: 'insertar_tag', as: 'insertar_tag'
      get 'remover_tag/:rfid', action: 'remover_tag', as: 'remover_tag'
      get 'limpiar_tags', action: 'limpiar_tags', as: 'limpiar_tags'
    end
  end
  resources :tags do
    collection do
      get 'por_rfid'
    end
  end
  resources :productos do
    member do
      get 'imagen'
    end
  end

  resources :cajas

  resource :supermercado

  devise_for :usuarios
  resources :usuarios

  defaults format: :json do
    post 'usuarios_app/login', to: 'usuarios_app#login'
    post 'usuarios_app/signup', to: 'usuarios_app#signup'
  end

  root 'dashboard#index'
end

server/app/models/producto.rb
require 'identicon'

class Producto < ApplicationRecord
  has_attached_file :imagen
  belongs_to :categoria

  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/

  validates :nombre, presence: true
  validates :precio, presence: true

  default_scope {
    order :nombre
  }

  before_save :generate_image

  private

  def generate_image
    return if imagen.present?

    uri_imagen = "#{Rails.root}/tmp/imagenes/#{id}_#{nombre}"
    carpeta = File.dirname(uri_imagen)
    FileUtils.mkdir_p(carpeta) unless File.directory?(carpeta)

    Identicon.file_for nombre, uri_imagen
    File.open(uri_imagen) do |file|
      self.imagen = file
    end
  end
end

server/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :authenticate_usuario!, except: [:index, :imagen]
  before_action :validar_gestion, except: [:index, :imagen]
  before_action :set_producto, only: [:show, :edit, :update, :destroy, :imagen]

  # GET /productos
  # GET /productos.json
  def index
    respond_to do |format|
      format.html {
        authenticate_usuario!
        validar_gestion
      }
      format.json {}
    end
    @productos = Producto.all
  end

  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        flash[:success] = 'Producto creado con éxito'
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        flash[:success] = 'Producto actualizado con éxito'
        format.html { redirect_to action: "index" }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    flash[:success] = 'Producto eliminado con éxito'
    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end

  def imagen
    send_file @producto.imagen.path, type: @producto.imagen.content_type, disposition: "inline"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio, :imagen, :apto_celiacos,
                                       :apto_diabeticos, :descripcion, :categoria_id)
    end
end

server/app/helpers/productos_helper.rb
module ProductosHelper
end

server/app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2>No se pudo guardar el producto</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :descripcion, "Descripción" %>
    <%= form.text_field :descripcion, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :categoria, "Categoría" %>
    <%= form.collection_select(:categoria_id, Categoria.all, :id, :nombre, {}, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= form.check_box :apto_celiacos %>
    <%= form.label :apto_celiacos, "Apto Celíacos" %>
  </div>

  <div class="form-group">
    <%= form.check_box :apto_diabeticos %>
    <%= form.label :apto_diabeticos, "Apto Diabéticos" %>
  </div>

  <div class="form-group">
    <%= form.label :precio %>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= form.number_field :precio, class: "form-control", step: 0.01 %>
    </div>
  </div>

  <% if producto.imagen.present? %>
    <%= image_tag producto.imagen.url, class: "imagen-producto" %>
  <% else %>
      <p>El producto no tiene una imagen cargada todavía.</p>
  <% end %>
  <div class="form-group">
    <%= form.label :imagen %>
    <%= form.file_field :imagen %>
  </div>

  <div class="row m-t-md">
    <div class="col-md-2 col-md-offset-4">
      <%= link_to productos_path, class: "btn btn-warning btn-block" do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
    </div>
    <div class="col-md-2">
      <button class="btn btn-primary btn-block" type="submit">
        <i class="fa fa-save"></i> Guardar
      </button>
    </div>
  </div>
<% end %>

server/app/views/productos/edit.html.erb
<% content_for :title do %>Productos<% end %>

<div class="row">
  <div class="col-md-12">
     <div class="ibox">
      <div class="ibox-title">
        <h5>Editar Producto</h5>
      </div>
      <div class="ibox-content">
        <%= render "form", producto: @producto %>
      </div>
    </div>
  </div>
</div>

server/app/views/productos/index.html.erb
<% content_for :title do %>Productos<% end %>

<div class="row">
  <div class="col-md-12">
     <div class="ibox">
      <div class="ibox-title">
        <h5>Listado de Productos</h5>
      </div>
      <div class="ibox-content">
        <% if @productos.any? %>
          <table class="table table-hover" id="tabla-productos">
            <thead>
              <tr>
                <th class="col-md-2">Nombre</th>
                <th class="col-md-3">Descripción</th>
                <th class="col-md-2">Categoría</th>
                <th class="col-md-2">Precio</th>
                <th class="col-md-1">Apto Celíacos</th>
                <th class="col-md-1">Apto Diabéticos</th>
                <th class="col-md-1"></th>
                <th class="col-md-1"></th>
              </tr>
            </thead>

            <tbody>
              <% @productos.each do |producto| %>
                <tr>
                  <td><%= producto.nombre %></td>
                  <td><%= producto.descripcion %></td>
                  <td><%= producto.categoria.nombre %></td>
                  <td><%= number_to_currency producto.precio %></td>
                  <td>
                    <% if producto.apto_celiacos %>
                      <span class="label label-primary">
                        <i class="fa fa-check"></i>
                      </span>
                    <% else %>
                      <span class="label label-danger">
                        <i class="fa fa-times"></i>
                      </span>
                    <% end %>
                  </td>
                  <td>
                    <% if producto.apto_diabeticos %>
                      <span class="label label-primary">
                        <i class="fa fa-check"></i>
                      </span>
                    <% else %>
                      <span class="label label-danger">
                        <i class="fa fa-times"></i>
                      </span>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_producto_path(producto), class: "btn btn-primary" do %>
                      <i class="fa fa-pencil"></i> Editar
                    <% end %>
                  </td>
                  <td>
                    <%= link_to producto, class: "btn btn-danger", method: :delete, data: { confirm: '¿Seguro?' } do %>
                      <i class="fa fa-trash"></i> Eliminar
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <div class="alert alert-warning">
            No hay productos cargados en el sistema.
          </div>
        <% end %>

        <br>

        <div class="row m-t-md">
          <div class="col-md-2 col-md-offset-5">
            <%= link_to new_producto_path, class: "btn btn-primary btn-block" do %>
              <i class="fa fa-plus"></i> Nuevo
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :local_scripts do %>
<script>
  $(document).ready(function () {
    $("#tabla-productos").DataTable();
  });
</script>
<% end %>

server/app/views/productos/new.html.erb
<% content_for :title do %>Productos<% end %>

<div class="row">
  <div class="col-md-12">
     <div class="ibox">
      <div class="ibox-title">
        <h5>Producto nuevo</h5>
      </div>
      <div class="ibox-content">
        <%= render "form", producto: @producto %>
      </div>
    </div>
  </div>
</div>