server/config/routes.rb
Rails.application.routes.draw do
  resources :promociones
  resources :categorias
  resources :changos do
    member do
      get 'qr'
      get 'insertar_tag/:rfid', action: 'insertar_tag', as: 'insertar_tag'
      get 'remover_tag/:rfid', action: 'remover_tag', as: 'remover_tag'
      get 'limpiar_tags', action: 'limpiar_tags', as: 'limpiar_tags'
    end
  end
  resources :tags do
    collection do
      get 'por_rfid'
    end
  end
  resources :productos do
    member do
      get 'imagen'
    end
  end

  resources :cajas

  resource :supermercado

  devise_for :usuarios
  resources :usuarios

  defaults format: :json do
    post 'usuarios_app/login', to: 'usuarios_app#login'
    post 'usuarios_app/signup', to: 'usuarios_app#signup'
  end

  root 'dashboard#index'
end

server/app/models/chango.rb
class Chango < ApplicationRecord
  has_many :tags

  def en_uso?
    tags.any? and tags.find do |tag| tag.disponible? end
  end

  def productos
    tags.map do |tag|
      tag.producto
    end.to_set
  end

  def productos_with_cantidad
    productos.map do |producto|
      {
        producto: producto,
        cantidad: tags.find_all do |tag|
          tag.producto == producto
        end.size
      }
    end
  end

  def total
    tags.sum do |tag|
      tag.producto.precio
    end
  end
end

server/app/controllers/changos_controller.rb
class ChangosController < ApplicationController
  before_action :authenticate_usuario!, except: [ :insertar_tag, :remover_tag, :limpiar_tags, :show]
  before_action :validar_gestion, except: [ :insertar_tag, :remover_tag, :limpiar_tags, :show ]
  before_action :set_chango, only: [
    :show, :edit, :update, :destroy, :qr, :insertar_tag, :remover_tag, :limpiar_tags
  ]
  before_action :set_rfid, only: [ :insertar_tag, :remover_tag ]

  # GET /changos
  # GET /changos.json
  def index
    @changos = Chango.all
  end

  # GET /changos/1.json
  def show
  end

  # GET /changos/new
  def new
    @chango = Chango.new
  end

  # GET /changos/1/edit
  def edit
  end

  # POST /changos
  # POST /changos.json
  def create
    @chango = Chango.new(chango_params)

    respond_to do |format|
      if @chango.save
        flash[:success] = 'Chango creado con éxito'
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @chango.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /changos/1
  # PATCH/PUT /changos/1.json
  def update
    respond_to do |format|
      if @chango.update(chango_params)
        flash[:success] = 'Chango actualizado con éxito'
        format.html { redirect_to action: "index" }
        format.json { render :show, status: :ok, location: @chango }
      else
        format.html { render :edit }
        format.json { render json: @chango.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /changos/1
  # DELETE /changos/1.json
  def destroy
    @chango.destroy
    flash[:success] = 'Chango eliminado con éxito'
    respond_to do |format|
      format.html { redirect_to changos_url }
      format.json { head :no_content }
    end
  end

  def insertar_tag
    @chango.tags << @tag
    @chango.save!
    flash[:success] = 'Tag insertado con éxito'
    respond_to do |format|
      format.html { render :edit }
      format.json { render :show, status: :ok, location: @chango }
    end
  end

  def remover_tag
    @chango.tags.delete @tag
    @chango.save!
    flash[:success] = 'Tag removido con éxito'
    respond_to do |format|
      format.html { render :edit }
      format.json { render :show, status: :ok, location: @chango }
    end
  end

  def limpiar_tags
    @chango.tags.delete_all
    flash[:success] = 'Tags removidos con éxito'
    respond_to do |format|
      format.html { render :edit }
      format.json { render :show, status: :ok, location: @chango }
    end
  end

  def qr
    qr = RQRCode::QRCode.new "#{@chango.id}|#{@chango.codigo}"
    send_data qr.as_png(size: 300).to_s, type: "image/png", disposition: "inline"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chango
      @chango = Chango.find(params[:id])
    end

    def set_rfid
      @tag = Tag.find_by_rfid params[:rfid]
      raise ActionController::RoutingError.new('RFID no encontrado') unless @tag
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chango_params
      params.require(:chango).permit(:codigo)
    end
end

server/app/helpers/changos_helper.rb
module ChangosHelper
end

server/app/views/changos/edit.html.erb
<% content_for :title do %>Changos<% end %>

<div class="row">
  <div class="col-md-12">
     <div class="ibox">
      <div class="ibox-title">
        <h5>Editar Chango</h5>
      </div>
      <div class="ibox-content">
        <%= render "form", chango: @chango %>
      </div>
    </div>

    <div class="ibox">
      <div class="ibox-title">
        <h5>Tags</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-stripped">
          <thead>
            <tr>
              <th class="col-md-4">Producto</th>
              <th class="col-md-6">Tag</th>
              <th class="col-md-2"></th>
            </tr>
          </thead>
          <tbody>
            <% if @chango.tags.empty? %>
              <tr>
                <td colspan="99" class="text-center">
                  <div class="alert alert-warning">
                    No hay tags asociados al chango
                  </div>
                </td>
              </tr>
            <% else %>
              <% @chango.tags.each do |tag| %>
                <tr>
                  <td><%= tag.producto.nombre %></td>
                  <td><%= tag.rfid %></td>
                  <td>
                    <%= link_to remover_tag_chango_path(@chango, tag.rfid), class: "btn btn-danger" do %>
                      <i class="fa fa-times"></i> Quitar manualmente
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

server/app/views/changos/index.html.erb
<% content_for :title do %>Changos<% end %>

<div class="row">
  <div class="col-md-12">
     <div class="ibox">
      <div class="ibox-title">
        <h5>Listado de Changos</h5>
      </div>
      <div class="ibox-content">
        <% if @changos.any? %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="col-md-6">ID</th>
                <th class="col-md-2">Código</th>
                <th class="col-md-2 text-center">Actualmente en Uso</th>
                <th class="col-md-2" colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @changos.each do |chango| %>
                <tr>
                  <td><%= chango.id %></td>
                  <td><%= chango.codigo %></td>
                  <td class="text-center">
                    <% if chango.en_uso? %>
                      <span class="label label-primary">
                        <i class="fa fa-check"></i>
                      </span>
                    <% else %>
                      <span class="label label-danger">
                        <i class="fa fa-times"></i>
                      </span>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to qr_chango_path(chango), class: "btn btn-success", download: "QR #{chango.codigo}" do %>
                      <i class="fa fa-arrow-down"></i> Descargar QR
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_chango_path(chango), class: "btn btn-primary" do %>
                      <i class="fa fa-pencil"></i> Editar
                    <% end %>
                  </td>
                  <td>
                    <%= link_to chango, class: "btn btn-danger", method: :delete, data: { confirm: '¿Seguro?' } do %>
                      <i class="fa fa-trash"></i> Eliminar
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <div class="alert alert-warning">
            No hay changos cargados en el sistema.
          </div>
        <% end %>

        <br>

        <div class="row m-t-md">
          <div class="col-md-2 col-md-offset-5">
            <%= link_to new_chango_path, class: "btn btn-primary btn-block" do %>
              <i class="fa fa-plus"></i> Nuevo
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

server/app/views/changos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @chango.codigo %>
</p>

<%= link_to 'Edit', edit_chango_path(@chango) %> |
<%= link_to 'Back', changos_path %>