server/config/routes.rb
Rails.application.routes.draw do
  resources :promociones
  resources :categorias
  resources :changos do
    member do
      get 'qr'
      get 'insertar_tag/:rfid', action: 'insertar_tag', as: 'insertar_tag'
      get 'remover_tag/:rfid', action: 'remover_tag', as: 'remover_tag'
      get 'limpiar_tags', action: 'limpiar_tags', as: 'limpiar_tags'
    end
  end
  resources :tags do
    collection do
      get 'por_rfid'
    end
  end
  resources :productos do
    member do
      get 'imagen'
    end
  end

  resources :cajas

  resource :supermercado

  devise_for :usuarios
  resources :usuarios

  defaults format: :json do
    post 'usuarios_app/login', to: 'usuarios_app#login'
    post 'usuarios_app/signup', to: 'usuarios_app#signup'
  end

  root 'dashboard#index'
end

server/app/views/layouts/_alerts.html.erb
<% if notice %>
	<div class="alert alert-info alert-dismissable">
		<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class="alert alert-danger alert-dismissable">
		<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
		<%= alert %>
	</div>
<% end %>

<% if flash[:error] %>
	<div class="alert alert-danger alert-dismissable">
		<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
		<%= flash[:error] %>
	</div>
<% end %>

<% if flash[:success] %>
	<div class="alert alert-info alert-dismissable">
		<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
		<%= flash[:success] %>
	</div>
<% end %>

server/app/views/layouts/_flash_alerts.html.erb
<script>
  $(function () {
    toastr.options = {
      "closeButton": true,
      "debug": false,
      "progressBar": true,
      "preventDuplicates": false,
      "positionClass": "toast-top-right",
      "onclick": null,
      "showDuration": "400",
      "hideDuration": "1000",
      "timeOut": "7000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }
      <% if flash[:success] %>
        toastr.success("<%= escape_javascript flash[:success] %>");
      <% end %>
      <% if flash[:warning] %>
        toastr.warning("<%= escape_javascript flash[:warning] %>");
      <% end %>
      <% if flash[:error] %>
        toastr.error("<%= escape_javascript flash[:error] %>");
      <% end %>
  });
</script>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="favicon.png">
    <title>SmartCart</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <script>
      $.fn.dataTable.defaults.language = {
        "sProcessing":     "Procesando...",
        "sLengthMenu":     "Mostrar _MENU_ registros",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
                "sFirst":    "Primero",
                "sLast":     "Último",
                "sNext":     "Siguiente",
                "sPrevious": "Anterior"
            },
        "oAria": {
                "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
      };
    </script>
  </head>
  <body>
    <!-- Wrapper-->
    <div id="wrapper">

      <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
          <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
              <div class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <span class="clear">
                    <span class="block m-t-xs">
                      <span>Usuario</span>
                      <strong class="font-bold block"><%= current_usuario.nombre %></strong>
                      <span class="block"><%= current_usuario.email %></span>
                    </span>
                  </span>
                </a>
              </div>
              <div class="logo-element">
                SC
              </div>
            </li>
            <% if current_usuario.es_gestion %>
              <li class="<% if controller_name == 'supermercados' %>active<% end %>">
                <%= link_to edit_supermercado_path do %>
                  <i class="fa fa-building-o"></i>
                  <span class="nav-label">Supermercado</span>
                <% end %>
              </li>
              <li class="<% if controller_name == 'promociones' %>active<% end %>">
                <%= link_to promociones_path do %>
                  <i class="fa fa-exclamation"></i>
                  <span class="nav-label">Promociones</span>
                <% end %>
              </li>
              <li class="<% if controller_name == 'categorias' %>active<% end %>">
                <%= link_to categorias_path do %>
                  <i class="fa fa-gift"></i>
                  <span class="nav-label">Categorías</span>
                <% end %>
              </li>
              <li class="<% if controller_name == 'productos' %>active<% end %>">
                <%= link_to productos_path do %>
                  <i class="fa fa-cube"></i>
                  <span class="nav-label">Productos</span>
                <% end %>
              </li>
              <li class="<% if controller_name == 'changos' %>active<% end %>">
                <%= link_to changos_path do %>
                  <i class="fa fa-shopping-cart"></i>
                  <span class="nav-label">Changos</span>
                <% end %>
              </li>
            <% end %>
            <% if current_usuario.es_tags %>
              <li class="<% if controller_name == 'tags' %>active<% end %>">
                <%= link_to tags_path do %>
                  <i class="fa fa-tag"></i>
                  <span class="nav-label">Tags</span>
                <% end %>
              </li>
            <% end %>
            <% if current_usuario.es_admin %>
              <li class="<% if controller_name == 'usuarios' %>active<% end %>">
                <%= link_to usuarios_path do %>
                  <i class="fa fa-users"></i>
                  <span class="nav-label">Usuarios</span>
                <% end %>
              </li>
            <% end %>
            <% if current_usuario.es_cajera %>
              <li class="<% if controller_name == 'cajas' %>active<% end %>">
                <%= link_to cajas_path do %>
                  <i class="fa fa-money"></i>
                  <span class="nav-label">Caja</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>

      <!-- Page wraper -->
      <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
          <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
              <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
              <li>
                <%= link_to destroy_usuario_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i> Log out
                <% end %>
              </li>
            </ul>
          </nav>
        </div>

        <div class="row wrapper border-bottom white-bg page-heading">
          <div class="col-lg-10">
            <h2><%= yield :title %></h2>
          </div>
        </div>

        <!-- Main view  -->
        <%= yield %>
      </div>

      <!-- Footer -->
      <div class="footer">
        <div>
          <strong>Copyright</strong> SmartCart &copy; 2018
        </div>
      </div>

    </div>
    <!-- End page wrapper-->

    <%= render 'layouts/flash_alerts' %>

    <%= yield :local_scripts %>
  </body>
</html>

server/app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>SmartCart</title>

		<!-- Main css styles -->
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

		<!-- Main javascript files -->
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= csrf_meta_tags %>

	</head>
	<body class="gray-bg">

		<div class="middle-box text-center loginscreen animated fadeinDown">
			<div>
				<%= render 'layouts/alerts' %>

				<%= yield %>

				<%= render "devise/shared/links" %>
			</div>
		</div>
	</body>
</html>