server/config/routes.rb
Rails.application.routes.draw do
  resources :promociones
  resources :categorias
  resources :changos do
    member do
      get 'qr'
      get 'insertar_tag/:rfid', action: 'insertar_tag', as: 'insertar_tag'
      get 'remover_tag/:rfid', action: 'remover_tag', as: 'remover_tag'
      get 'limpiar_tags', action: 'limpiar_tags', as: 'limpiar_tags'
    end
  end
  resources :tags do
    collection do
      get 'por_rfid'
    end
  end
  resources :productos do
    member do
      get 'imagen'
    end
  end

  resources :cajas

  resource :supermercado

  devise_for :usuarios
  resources :usuarios

  defaults format: :json do
    post 'usuarios_app/login', to: 'usuarios_app#login'
    post 'usuarios_app/signup', to: 'usuarios_app#signup'
  end

  root 'dashboard#index'
end

server/app/controllers/cajas_controller.rb
class CajasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :validar_cajera

  def index
    @changos = Chango.all.find_all do |chango|
      chango.en_uso?
    end
  end

  def edit
    @chango = Chango.find(params[:id])
  end

  def update
    Tag.transaction do
      tag_ids = params[:chango][:tags].map do |tag|
        Tag.find tag.to_i
      end.each do |tag|
        tag.pagado!
        tag.save!
      end
    end

    flash[:success] = "Chango cobrado con éxito"
    redirect_to action: "index"
  end
end

server/app/views/cajas/_form.html.erb
<%= form_with(model: chango, local: true) do |form| %>
  <% if chango.errors.any? %>
    <div id="error_explanation">
      <h2>No se pudo guardar el chango</h2>

      <ul>
      <% chango.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :codigo %>
    <%= form.text_field :codigo, class: "form-control" %>
  </div>

  <div class="row m-t-md">
    <div class="col-md-2 col-md-offset-4">
      <%= link_to changos_path, class: "btn btn-warning btn-block" do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
    </div>
    <div class="col-md-2">
      <button class="btn btn-primary btn-block" type="submit">
        <i class="fa fa-save"></i> Guardar
      </button>
    </div>
  </div>
<% end %>

server/app/views/cajas/edit.html.erb
<% content_for :title do %>Caja<% end %>

<div class="row">
  <div class="col-md-12">
     <div class="ibox">
      <div class="ibox-title">
        <h5>Pagar Chango</h5>
      </div>
      <div class="ibox-content">
        <%= form_with(model: @chango, url: caja_path, local: true) do |form| %>
          <% @chango.tags.each do |tag| %>
            <%= form.hidden_field :tags, value: tag.id, multiple: true %>
          <% end %>
          <table class="table table-stripped">
            <thead>
              <tr>
                <th class="col-md-2 text-right">Cantidad</th>
                <th class="col-md-4">Producto</th>
                <th class="col-md-2 text-right">Precio Unitario</th>
                <th class="col-md-2 text-right">Precio Total</th>
              </tr>
            </thead>
            <tbody>
              <% if @chango.tags.empty? %>
                <tr>
                  <td colspan="99" class="text-center">
                    <div class="alert alert-warning">
                      No hay productos en el chango
                    </div>
                  </td>
                </tr>
              <% else %>
                <% @chango.productos_with_cantidad.each do |producto_with_cantidad| %>
                  <% producto = producto_with_cantidad[:producto] %>
                  <% cantidad = producto_with_cantidad[:cantidad] %>
                  <tr>
                    <td class="text-right"><%= cantidad %></td>
                    <td><%= producto.nombre %></td>
                    <td class="text-right"><%= number_to_currency producto.precio %></td>
                    <td class="text-right"><%= number_to_currency(producto.precio * cantidad) %></td>
                  </tr>
                <% end %>
                <tr>
                  <th></th>
                  <th></th>
                  <th class="text-right">Total:</th>
                  <th class="text-right"><%= number_to_currency @chango.total %></th>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="row m-t-md">
            <div class="col-md-2 col-md-offset-4">
              <%= link_to cajas_path, class: "btn btn-warning btn-block" do %>
                <i class="fa fa-arrow-left"></i> Volver
              <% end %>
            </div>
            <div class="col-md-2">
              <button class="btn btn-primary btn-block" type="submit">
                <i class="fa fa-dollar"></i> Cobrar
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

server/app/views/cajas/index.html.erb
<% content_for :title do %>Caja<% end %>

<div class="row">
  <div class="col-md-12">
     <div class="ibox">
      <div class="ibox-title">
        <h5>Changos en Uso</h5>
      </div>
      <div class="ibox-content">
        <% if @changos.any? %>
          <table class="table table-stripped">
            <thead>
              <tr>
                <th class="col-md-2">Código</th>
                <th class="col-md-6">Productos</th>
                <th class="col-md-2 text-right">Total</th>
                <th class="col-md-2"></th>
              </tr>
            </thead>

            <tbody>
              <% @changos.each do |chango| %>
                <tr>
                  <td><%= chango.codigo %></td>
                  <td>
                    <%= truncate(chango.productos.map { |p| p.nombre }.join ", ") %>
                  </td>
                  <td class="text-right">
                    <%= number_to_currency(chango.total) %>
                  </td>
                  <td class="text-right">
                    <%= link_to edit_caja_path(chango), class: "btn btn-primary" do %>
                      <i class="fa fa-dollar"></i> Cobrar
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <div class="alert alert-warning">
            No hay changos con productos que no estén pagos
          </div>
        <% end %>

        <br>
      </div>
    </div>
  </div>
</div>